services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ksj
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME_PG}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PG}
      POSTGRES_DB: hotelservice
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  mongo-db:
    image: mongo:7
    container_name: mongo-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-network

  service-registry:
    image: service-registry
    container_name: service-registry-container
    ports:
      - "8761:8761"
    depends_on:
      - mysql-db
      - postgres-db
      - mongo-db
    networks:
      - microservices-network

  api-gateway:
    image: api-gateway
    container_name: api-gateway-container
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
    networks:
      - microservices-network

  hotel-service:
    image: hotel-service
    container_name: hotel-service-container
    ports:
      - "8082:8082"
    environment:
      DB_USERNAME_PG: ${DB_USERNAME_PG}
      DB_PASSWORD_PG: ${DB_PASSWORD_PG}
    depends_on:
      - service-registry
      - postgres-db
    networks:
      - microservices-network

  rating-service:
    image: rating-service
    container_name: rating-service-container
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - mongo-db
    networks:
      - microservices-network

  user-service:
    image: user-service
    container_name: user-service-container
    ports:
      - "8081:8081"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - service-registry
      - mysql-db
      - hotel-service
      - rating-service
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true

volumes:
  mysql_data:
  postgres_data:
  mongo_data: