spring.datasource.url=jdbc:postgresql://localhost:5432/hotelservice
spring.datasource.username=${DB_USERNAME_PG}
spring.datasource.password=${DB_PASSWORD_PG}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true