spring.datasource.url=jdbc:postgresql://postgres-db:5432/hotelservice
spring.datasource.username=${DB_USERNAME_PG}
spring.datasource.password=${DB_PASSWORD_PG}

eureka.client.service-url.defaultZone=http://service-registry-container:8761/eureka
eureka.instance.prefer-ip-address=true